apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      preSync:
        exec:
          command: ["/bin/bash", "-c", "kubectl annotate app my-app-deployment annotation-key=$(kubectl get app my-app-deployment -ojsonpath='{.metadata.annotations.annotation-key}' | awk '{print $1 + 1}')"]
      containers:
        - name: my-app-container
          image: my-app-image:latest
          ports:
            - containerPort: 8080
